### ISSUE TITLE
Support for other languages in syntax?

### ISSUE THREAD

**Issue by SaraVieira** [pomber/code-surfer#12]
Heey !

This is amazing and I am in love !

I am doing a presentation that shows some HTML code and I was just wondering if there is support for other languages or if it's something I am missing in mdx-deck ?

**Comment by pomber** [comment]
Hi Sara. Yes! there's an undocumented prop: `lang` (the default is "jsx").
You can use any language supported by [react-prism-renderer](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) (There's no "html" in the list but I guess "markup" should work).

Let me know if you are having any problem with it, I haven't tested other languages too much.

**Comment by SaraVieira** [comment]
Hey !

So this is my code:

```js

<CodeSurfer
  title="Header"
  theme={nightOwl}
  lang="markup"
  code={`
  <div>
    <a href="..">
      <span>
        <strong>Sara Vieira</strong>
        <small class="time">
          Aug 23
        </small>
      </span>
    </a>
  </div>
  `}
 steps={[
    { lines: [1, 10] }
  ]}
/>
```

And this how it looks:

<img width="994" alt="screen shot 2018-08-29 at 18 04 12" src="https://user-images.githubusercontent.com/1051509/44800140-f43f0080-abb5-11e8-9d90-0d931306c11a.png">

**Comment by SaraVieira** [comment]
I'm gonna close this as it's not code-surfer and update the docs :)

Thanks :)

**Comment by kitten** [comment]
@SaraVieira `markup` is the correct one and we're including it in fact in our custom Prism vendored build:

https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

But I think we're missing aliases, so I'll have to add those so that `html` maps to `markup` and so on

**Comment by SaraVieira** [comment]
Markup makes sense since it's the name prism uses too :)

My question is if that is highlighted because I don't think so :(

**Comment by kitten** [comment]
@SaraVieira hmm, you're right that's actually incorrect. I assumed that `plain` tokens need to use the default colour, but they should actually cascade as usual

**Comment by SaraVieira** [comment]
Bless you man! Glad I bought dank now

**Comment by kitten** [comment]
@SaraVieira Published a fix under `0.1.3`. Feel free to give it a whirl :)

**Comment by pomber** [comment]
JSX looks much better now (https://mdx-deck-code-surfer-theming.netlify.com/#2).  
I'm not sure how npm versions work so I published a new version just in case.  
Thanks a lot @kitten and @SaraVieira

**Comment by SaraVieira** [comment]
Look at this amazing HTML 😍

<img width="1424" alt="screen shot 2018-08-29 at 20 47 01" src="https://user-images.githubusercontent.com/1051509/44808502-b7cacf00-abcc-11e8-9adb-e28f637902d0.png">

Thanks to you both :D

**Comment by pomber** [comment]
Tip: If you add an empty note the code will be closer to the vertical center

**Comment by SaraVieira** [comment]
Now we dope !

Look at this aswesome HTML
<img width="1424" alt="screen shot 2018-08-29 at 23 10 33" src="https://user-images.githubusercontent.com/1051509/44815790-c4592280-abe0-11e8-91f0-50b3d735b7b8.png">

Thanks man !

**Comment by vlsi** [comment]
I guess this might help others who struggle with adding new languages.

packages.json:
```js
  "devDependencies": {
    "mdx-deck": "^1.10.2",
    "mdx-deck-code-surfer": "^0.5.5",
    "prismjs": "^1.15.0",
    "raw-loader": "^0.5.1"
  },
  "dependencies": {
    "styled-components": "^4.1.3"
  }
```

This configuration has no support for Kotlin, however the following unlocks that syntax for me (the code is placed at the top of `deck.mdx`):

```js
import { default as Prism } from 'prism-react-renderer/prism'
import kotlinLang from 'react-syntax-highlighter/languages/prism/kotlin'
kotlinLang(Prism) // <-- add Kotlin syntax
```

**Comment by vlsi** [comment]
Just for the reference, here's how I add syntax highlighting to the current code-surfer:

```
  "devDependencies": {
    "code-surfer": "3.1.0",
    "mdx-deck": "3.0.13"
  },
```

`deck.mdx`:
```js
import 'prismjs/components/prism-kotlin';
```
