### ISSUE TITLE
Custom theme from mdx-deck not being passed down

### ISSUE THREAD

**Issue by kutyel** [pomber/code-surfer#18]
Well so I have a custom theme like this:
```js
import theme from 'mdx-deck/themes'

export default {
  ...theme,
  monospace: 'Dank Mono',
  colors: {
    text: '#d4d4d4',
    background: '#1e1e1e'
  }
}
```

And in the standalone code in the slides `<SomeCode />` it works fine but code-surfer (or maybe prism-react-renderer? @kitten) is not picking it up... very minor stuff but just to inform and also I'm willing to submit a PR if pointed in the right direction 😉 

Thank you for everything!! 👏

Thanks to you and to @jxnblk our slides are gonna be dope! 💪

**Comment by pomber** [comment]
What props are you passing to CodeSurfer?

If you are using the `theme` prop it will use the text and backgroundColor from the prism-react-renderer theme. Not sure about the monospace.

**Comment by kutyel** [comment]
The usual:
```jsx
<Code
  theme={vsDarkPlus}
  title='before'
  code={require('!raw-loader!./components/datepicker.js')}
  steps={[
    { lines: [6], notes: 'Note for the first step' },
    { range: [5, 9] },
    { tokens: { 9: [3, 4, 5] }, notes: 'Note for the third step' }
  ]}
/>
```
Apparently, `monospace` is a theme config from **mdx-deck**, but it's not being used in code-surfer 🤔

**Comment by SaraVieira** [comment]
Oh yeah , I get the same now that I notice :(

**Comment by SaraVieira** [comment]
Seems that the theme is always undefined

**Comment by pomber** [comment]
Regarding monospace: I think I fixed it in v0.3.0 (you'll need to update mdx-deck to last version (1.7.0) too).  

For text and background, I don't know. It's a matter of which theme takes precedence: mdx-deck theme or prism-react-renderer theme. I'm open to suggestions.

**Comment by kutyel** [comment]
That worked! Thank you!! 🎉 ❤️

**Comment by SaraVieira** [comment]
<img width="1424" alt="screen shot 2018-08-30 at 16 12 43" src="https://user-images.githubusercontent.com/1051509/44857264-aedf0980-ac6f-11e8-9851-b0801828da3a.png">
YAAAY
