### ISSUE TITLE
console.log left in released code

### ISSUE THREAD

**Issue by trevordmiller** [pomber/code-surfer#21]
![image](https://user-images.githubusercontent.com/5497885/44826846-b64dd680-abcd-11e8-812f-c6714cbc4ffc.png)

![image](https://user-images.githubusercontent.com/5497885/44826897-dbdae000-abcd-11e8-91e4-f99033b2f9f6.png)

If a suggestion is helpful, I like using eslint + `eslint:recommended` with a pre-commit hook and/or CI to prevent shipping stuff like this so I don't have to think about it.

**Comment by pomber** [comment]
CI is in my to-do list. Do you want to send a PR for the console.log?
