### ISSUE TITLE
Initial step / Default step

### ISSUE THREAD

**Issue by tobiastimm** [pomber/code-surfer#28]
Would be cool, if you can define a step as the initial state.

Use-Case:

I want to show  the differences in one css property between slides for example.

Your component rocks! 🤘

**Comment by pomber** [comment]
Good idea, do you have any particular API in mind? Maybe a boolean prop for starting from the first step instead of starting with the full code

**Comment by tobiastimm** [comment]
A boolean would be great. I don't think that you need to specify a particular step atm.

**Comment by pomber** [comment]
Now it always use the first step from the step prop as the real first step. And if you have multiple steps and want the previous behavior you need to explicitly add a first step where you show all the code (an empty object `{}` in a step tells code surfer to show everything).
