### ISSUE TITLE
Zoom-in moves code on left side out of the window

### ISSUE THREAD

**Issue by kabl** [pomber/code-surfer#29]
Hi thanks for your amazing work.

When zooming in from a big code snippet, whole text is moved outside on the left side. See the screenshots. 

I used your 'sample.mdx' deck:

```js
<CodeSurfer
  title="Scale and Scroll 2"
  notes="Long snippets are scaled ⬇️"
  code={require("!raw-loader!../tronix.sol")}
  steps={[
    { range: [1, 3], notes: "⬇️" },
    { range: [5, 13], notes: "⬇️" },
    { range: [15, 32], notes: "⬇️" },
    { lines: [30, 35], notes: "⬇️" },
    { range: [15, 32], lines: [40], notes: "➡️" }
  ]}
/>
```
code snipppet can be found here: https://etherscan.io/address/0xf230b790e05390fc8295f4d3f60332c93bed42e2#code 

![image](https://user-images.githubusercontent.com/4295394/44947268-036abc00-ae0b-11e8-9843-0bcfe938ac83.png)
![image](https://user-images.githubusercontent.com/4295394/44947272-15e4f580-ae0b-11e8-9e02-be4b8f2dad3f.png)

**Comment by GazzaHazza** [comment]
I am also noticing this! Is there any solution?

**Comment by pomber** [comment]
Hi! for my decks I try to keep the code in less than 50 columns (with prettier `"printWidth": 50`).  

I'm planning to make this more responsive to the viewport and code width (#2), but having very long lines will still be a problem.

**Comment by jhonparedes** [comment]
Hi. I was also having this problem when I was making code-surfer slides. I was able to find a temp fix. 

If you pass it a custom layout, you can change the `font-size`

```
import Layout from './layout.js';
---
export default Layout
<CodeSurfer
  theme={vsDarkPlus}
   ...
```

```
// layout.js
import React from 'react'
export default ({ children }) =>
  <div style={{ fontSize: '19px' }}> {children} </div>
```

And changing the font-size, depending on how big my code was. 

See screenshots below. 

I don't know if that'll solve OP's problem or is a permanent fix. Maybe `<CodeSurfer>` can take fontSize as a props; though as pomper said he's planning on making it more responsive, so it might be a moot point. 

**Without layout.js**
<img width="1615" alt="withoutlayout" src="https://user-images.githubusercontent.com/5641734/45016756-7ece9800-afda-11e8-94dc-b0c76c3da87a.png">

**With layout.js**
<img width="1611" alt="withlayout" src="https://user-images.githubusercontent.com/5641734/45016755-7ece9800-afda-11e8-8b2c-074607cbb057.png">

**Comment by Fetz** [comment]
https://github.com/pomber/code-surfer/issues/29#issuecomment-418155285

Sadly, that prettier option doesn't work well when using jest inlineSnapshots

**Comment by mohseenrm** [comment]
Fix by @snesjhon works! maybe fluid `font-size` as props helps?

**Comment by Relequestual** [comment]
Having an issue with a long line being added (96 cols).
This is a an auto formatted JSON file, so I can't change it.
I'd like the line to be wrapped, but I can't see a way to do this.

Open to suggestions. I could not wrangle the css either =[

**Comment by pomber** [comment]
Should be fixed in v3
