### ISSUE TITLE
Document how to install "raw-loader" in examples

### ISSUE THREAD

**Issue by trevordmiller** [pomber/code-surfer#3]
And should it be a `--save` `dependency`, or a `--save-dev` `devDependency`?

**Comment by trevordmiller** [comment]
When using syntax like this in `mdx-deck`:

```jsx
---

import { CodeSurfer } from "mdx-deck-code-surfer"

<CodeSurfer
  title="SomeComponent"
  notes="Start with this note"
  code={require("raw-loader!./components/SomeComponent")}
  showNumbers={true}
  steps={[
    { range: [1, 3], notes: "Some note" },
    { lines: [6, 10], notes: "Some note" },
    { range: [13, 18], notes: "Some note" },
    { lines: [20], notes: "Some note" }
  ]}
/>

---

```

I'm getting compiled output like this:

![image](https://user-images.githubusercontent.com/5497885/44630633-00109580-a91e-11e8-9f5e-01897cd6e00d.png)

**Comment by trevordmiller** [comment]
I tried both `npm install --save raw-loader` and `npm install --save-dev raw-loader` with the same result.

**Comment by pomber** [comment]
That's because mdx-deck webpack config is loading the `.js` files with babel.

A workaround is to change the extension of the file to `.jsx` and require it with the extension:
```
code={require("raw-loader!./components/SomeComponent.jsx")}
```

---

So, the issues to fix are:
- Better `raw-loader` usage docs
- Docs for loading `.js` (and `.mdx`) files -- or even better a zero-config way to load them

**Comment by trevordmiller** [comment]
@pomber Thanks for the info. The workaround feels brittle - if mdx-deck adds support for `.jsx` it will break in the same way as `.js`. Also, `.jsx` doesn't work if you want to both show the code and render it in your `mdx-deck` from the same source file. For example:

**`components/SomeComponent/index.jsx`**

```jsx
---

import SomeComponent from './components/SomeComponent/index.jsx'

<SomeComponent />

---

import { CodeSurfer } from "mdx-deck-code-surfer"

<CodeSurfer
  title="SomeComponent"
  code={require("raw-loader!./components/SomeComponent/index.jsx")}
  showNumbers={true}
  notes="Some starting note"
  steps={[
    { range: [1, 3], notes: "Some step note 1" },
    { lines: [5, 10], notes: "Some step note 2" },
    { range: [15, 20], notes: "Some step note 3" },
    { lines: [22], notes: "Some step note 4" }
  ]}
/>
```

![image](https://user-images.githubusercontent.com/5497885/44631585-749e0100-a92b-11e8-8047-2b88286bd35c.png)

It would be nice if the conventional `.js` extension could be used instead so that rendering in `mdx-deck` still works and `CodeSurfer` could display that source code from the same `.js` file source:

**`components/SomeComponent/index.js`**

```jsx
---

import SomeComponent from './components/SomeComponent'

<SomeComponent />

---

import { CodeSurfer } from "mdx-deck-code-surfer"

<CodeSurfer
  title="SomeComponent"
  codePath='./components/SomeComponent'
  showNumbers={true}
  notes="Some starting note"
  steps={[
    { range: [1, 3], notes: "Some step note 1" },
    { lines: [5, 10], notes: "Some step note 2" },
    { range: [15, 20], notes: "Some step note 3" },
    { lines: [22], notes: "Some step note 4" }
  ]}
/>
```

**Comment by spicydonuts** [comment]
Also running into this. Since I want to use the component in the slides as well as as CodeSurfer source this workaround won't work without copying the file (mdx-deck won't load .jsx files).

**Comment by pomber** [comment]
Didn't know about that option, that's exactly what we need!  
I'll change the sample to use that and add it to the docs.

**Comment by spicydonuts** [comment]
Depends on whether `mdx-deck` is a dev dep.

It seems `mdx-deck build` doesn't work if I use `CodeSurfer`.. I get this:

```
[mdx-deck] building
[mdx-deck] rendering static html
Missing HeadProvider
[err] TypeError: Cannot read property 'step' of null
    at _class2.render (./node_modules/mdx-deck-code-surfer/dist/deck-code-surfer.js:93:30)
    at processChild (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at renderToString (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2729:25)
    at renderHTML (./node_modules/mdx-deck/lib/html.js:57:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by spicydonuts** [comment]
I'm not sure the `Missing HeadProvider` bit is relevant, since it also prints when I delete the slide using `CodeSurfer` and the build works.

**Comment by trevordmiller** [comment]
I'm using `mdx-deck` as a dev dependency, since that is what the `mdx-deck` readme shows:
https://github.com/jxnblk/mdx-deck

**Comment by pomber** [comment]
@spicydonuts I think I broke `mdx-deck build` in the last version. Thanks for the report. Could you move it to a new issue?  
@trevordmiller I updated the readme with the correct usage of raw-loader.

**Comment by trevordmiller** [comment]
Just tested the latest documentation. Works great! Thanks so much :)
