### ISSUE TITLE
Can't display most ReasonML code

### ISSUE THREAD

**Issue by sslotsky** [pomber/code-surfer#31]
Really impressed with this lib, thank you for all your work! Running into a strange issue trying to display ReasonML code. This simple example works:

```js
<CodeSurfer
  title="Some MFing ReasonML Code"
  notes="Betcha didn't see that shit coming"
  code="let foo = 2.0;"
  lang="reason"
  showNumbers={false}
  dark={false}
  steps={[
    { lines: [1], notes: "Note for the first step" }
  ]}
/>
```
But here's one that doesn't:

```js
<CodeSurfer
  title="Some MFing ReasonML Code"
  notes="Betcha didn't see that shit coming"
  code="open Common;"
  lang="reason"
  showNumbers={false}
  dark={false}
  steps={[
    { lines: [1], notes: "Note for the first step" }
  ]}
/>
```

This code causes 5 instances of this error in the console:

```
Uncaught Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
```

I found at least a few instances of ReasonML code that caused this error. Please let me know if there's more info that I can provide!

**Comment by pomber** [comment]
Thanks! Looks like it's an issue with prism-react-renderer. I opened FormidableLabs/prism-react-renderer#11

**Comment by sslotsky** [comment]
Thank _you_ for the speedy reply!

**Comment by kitten** [comment]
Has been merged and a new `prism-react-renderer` release is out :+1: https://github.com/FormidableLabs/prism-react-renderer/pull/12

So just upgrade prism-react-renderer and it'll work just fine :)
