### ISSUE TITLE
Allow for `theme` customization

### ISSUE THREAD

**Issue by kutyel** [pomber/code-surfer#4]
Hi!

Huge thanks and props @pomber for creating this! Works like a charm 👌 🎉 

Just a small detail: I'm trying to customise the color theme for the actual code, to look more similar to for example the default vscode theme for code, but it seems that it doesn't open up the `theme` prop right now, also the titles inside `<CodeSurfer>` don't seem to receive the `theme` from *mdx-deck* either 😕 

I've spoken with @kitten and apparently `prism-react-renderer` already has a theming option, but we need to pass it down 😉 

Thanks for everything and please tell me if I can help you with a small PR! 👏

**Comment by pomber** [comment]
Hi!

I think the change isn't too big, if you want to try it see this line: 
https://github.com/pomber/code-surfer/blob/master/packages/code-surfer/src/code-surfer.js#L29

Adding a theme property to that component and changing the condition to something like `theme={theme !== undefined ? theme : dark ? darkTheme : lightTheme}` (I explicitly check against undefined because null is a valid theme for prism-react-rederer).

I think that should be enough at least for a short-term solution.

**Comment by kitten** [comment]
@pomber I think a longterm solution would include to add the prism-react-renderer theme to mdx's theme as well eventually.

Maybe they can even be convinced to switch code blocks over to it?

**Comment by kutyel** [comment]
@kitten oh, that's right, I'd like to use Night Owl from prims-react-renderer for example, the themes from mdx-deck seem to be pretty simple regarding code highlighting, @jxnblk what do you think? 😉

**Comment by pomber** [comment]
Thanks for the PR @kutyel !

@kitten what API do you have in mind?  
Current mdx-deck themes for syntax highlighting look like this:
```
// example theme.js
import { future } from 'mdx-deck/themes'
import okaidia from 'react-syntax-highlighter/styles/prism/okaidia'
import prismRuby from 'react-syntax-highlighter/languages/prism/ruby'

export default {
  ...future,
  prism: {
    style: okaidia,
    languages: {
      ruby: prismRuby
    }
  }
}
```

**Comment by jxnblk** [comment]
I would happily accept a PR for using prism-react-renderer for mdx-deck code blocks. As for theming for this particular component, I'm guessing that mdx-deck themes could use an object named `CodeSurfer` (or similar) and pass the whole thing along

**Comment by pomber** [comment]
I added some [examples for using it with prism-react-renderer](https://mdx-deck-code-surfer-theming.netlify.com). I couldn't make it work with prism themes yet (tried something like [this](https://github.com/pomber/code-surfer/blob/master/packages/mdx-deck-code-surfer/docs/snippets/okaidia.mdx)).

**Comment by pomber** [comment]
Closing this one. Now you can also set the theme globally: https://codesurfer.js.org/sample/#10
