### ISSUE TITLE
Can we change code size?

### ISSUE THREAD

**Issue by JJ** [pomber/code-surfer#41]
How could we change the font size?

**Comment by pomber** [comment]
I think you could do something like this:
```jsx
<div style={{fontSize: 10}}>
  <CodeSurfer code="console.log(`Hello`);" />
</div>
```

We could add support for the `style` prop: `<CodeSurfer code="console.log('Hello');" style={{fontSize: 10}} />`. It should be an easy PR if anyone wants to try.

**Comment by valentingalea** [comment]
Your suggestion doesn't work...

**Comment by vsantos** [comment]
I know that this is an old issue but I want to give my 50 cents.

@valentingalea , @pomber's suggestion is working like a charm for me using `v0.5`. I'm using the following code:

```
<div style={{fontSize: 26}}>
  <CodeSurfer
    title='bar.go'
    lang='go'
    showNumbers={true}
    dark={false}
    code={require('!raw-loader!./snippets/foo/bar.go')}
  />
</div>
```

 Here is my `package.json` for reference:

```
  "devDependencies": {
    "mdx-code": "^1.1.3",
    "mdx-deck": "1.10.2",
    "mdx-deck-code-surfer": "v0.5.5",
    "mdx-deck-live-code": "^1.0.0",
    "raw-loader": "^1.0.0"
  }
```

I hope it helps!

**Comment by ankeetmaini** [comment]
@pomber can you point me on how to do this in v2? :)

**Comment by pomber** [comment]
@ankeetmaini check the [custom styles docs](https://codesurfer.pomb.us/#custom-styles)

**Comment by jsjoeio** [comment]
Has anyone figured out how to do this in v3?
