### ISSUE TITLE
Problems deploying to now.sh

### ISSUE THREAD

**Issue by JJ** [pomber/code-surfer#42]
This; https://github.com/JJ/git-push works locally without a problem, however, I can't deploy with now; it stops with this error in the log:

```
var _mdxDeckCodeSurfer = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'mdx-deck-code-surfer'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
```

Here's the whole log, just in case: https://zeit.co/jjmerelo/git-push/duypo66h6

Any idea?

**Comment by sibelius** [comment]
cc @paulogdm

**Comment by paulogdm** [comment]
The log is private.
It seems you are confused about builders:
```
{
  "version": 2,
  "builds": [
    { "src": "git-push.mdx", "use": "@now/node-server" }
  ]
}
```
Please, take a look at our examples [here](https://github.com/zeit/now-examples).
Also, do notice that we have a `mdx-deck` builder, so you may want to try:
```
{
  "version": 2,
  "builds": [
    { "src": "git-push.mdx", "use": "@now/mdx-deck" }
  ]
}
```

**Comment by JJ** [comment]
This was some time ago, but if I remember correctly, I couldn't use mdx-deck because my deck had some plugins that weren't picked up by the builder. So I'm clearly confused about something, but I'm afraid *not* about builders.

**Comment by paulogdm** [comment]
We improved the builder a lot since November. Could you try to redeploy?

**Comment by JJ** [comment]
I'll try that. Thanks.
