### ISSUE TITLE
Symbols duplicated in non-focus code

### ISSUE THREAD

**Issue by BrendanFDMoore** [pomber/code-surfer#43]
Hey there,

Loving Code Surfer with `mdx-deck`, but noticed an odd issue with some duplicated symbols in "background" (non-focused) code snippets.

eg: `=` would appear as `==` or `:` appear as `::`

When the same line of code is focused, the corruption goes away.

This is not a huge, deal, just confusing when an unfamiliar audience is trying to glean a bit of extra context from the background lines.

Example of this:
![code-surfer-bug](https://user-images.githubusercontent.com/4238814/48995807-7c7e6480-f117-11e8-8af9-51a6d2ca615c.gif)

I've noticed this in two different presentations now, so I don't think it's a one-off.

Happy to help diagnose further.

**Comment by pomber** [comment]
Thanks. Can you share a sample mdx? also what mdx-deck-code-surfer version are you using?
