### ISSUE TITLE
Problem with code surfer and mdx-deck-live-code

### ISSUE THREAD

**Issue by sibelius** [pomber/code-surfer#49]
it is rendering this:

![image](https://user-images.githubusercontent.com/2005841/52005513-039ddf00-24b1-11e9-80a0-687458c9c563.png)

it does not take `\n` new lines in consideration and it does not have syntax hightlight either

---
<CodeSurfer
  title="Sum Type"
  lang="javascript"
  code={require('!raw-loader!./samples/sumType.js')} />
---

you can reproduce here https://github.com/sibelius/functional-types-abstractions/blob/master/src/deck.mdx#L443

`yarn start`

here is the sumType file https://github.com/sibelius/functional-types-abstractions/blob/master/src/samples/sumType.js

**Comment by pomber** [comment]
Thanks, could you make a smaller repro with minimal dependencies and slides?

**Comment by sibelius** [comment]
is this minimal enough https://github.com/sibelius/relay-modern-future/blob/master/src/deck.mdx#L23?

**Comment by sibelius** [comment]
the problem is not in raw-loader, it is keeping the space

I got the code surfer working well, when adding or remove lang prop

if I remove lang={javascript}, code surfer just works

however if I remove and then start mdx-deck again, it will be broke, then I add it back, and the render works well

**Comment by sibelius** [comment]
removing https://github.com/JReinhold/mdx-deck-live-code solves the issue as well

**Comment by pomber** [comment]
:confused: but you are not using mdx-deck-live-code in [https://github.com/sibelius/relay-modern-future/blob/master/src/deck.mdx](https://github.com/sibelius/relay-modern-future/blob/master/src/deck.mdx)

**Comment by sibelius** [comment]
not anymore

I think we can close, and investigate more later on \o/

**Comment by sakhisheikh** [comment]
I am getting the same issue with mdx-deck-live-code

![image](https://user-images.githubusercontent.com/18448824/52665663-edbb0000-2f2d-11e9-82c2-8fadc36f84d8.png)

**Comment by yuyao17** [comment]
Im having the same problem, and removing live code did the trick but is there a workaround?

**Comment by yuyao17** [comment]
it seems like both libraries use prism and one is overriding the other

**Comment by yuyao17** [comment]
@pomber any way to fix?

**Comment by yuyao17** [comment]
I really want to use both
