### ISSUE TITLE
Give render control back

### ISSUE THREAD

**Issue by jaredpalmer** [pomber/code-surfer#5]
It would be ideal if `title` and `notes` could take either strings or components so that consumers can have full control over the look of their presentation. 

For example, would love for my notes too look like:

![code-surf-note](https://user-images.githubusercontent.com/4060187/44660310-365d1c00-a9d5-11e8-8ecb-8dd10af61330.png)

```jsx
<CodeSurfer
  title={() => <div style={{ ... }}>Some Title</div>}}
  notes="Start with this note"
  code={require("!raw-loader!./my-snippet.js")}
  showNumbers={false}
  dark={false}
  steps={[
    { lines: [6], notes: "Note for the first step" },
    { range: [5, 9] },
    { tokens: { 9: [3, 4, 5] }, notes: () => <div style={{ ... }}>Note for the third step</div> }
  ]}
/>
```

**Comment by trevordmiller** [comment]
This talk might be helpful for this - showing how to use render props to give full presentation control to users:
https://www.youtube.com/watch?v=AiJ8tRRH0f8

**Comment by pomber** [comment]
https://mdx-deck-code-surfer.netlify.com/#8
