### ISSUE TITLE
Seems to be incompatible with mdx-deck 2.0

### ISSUE THREAD

**Issue by emirotin** [pomber/code-surfer#53]
First, a peer dep of styled-components is required for it to work and it's not mentioned in the readme

Second, it fails with `withDeck` not being a function

**Comment by emirotin** [comment]
WRT the first one mdx-deck has switched to emotion and is now using emotion-theming.
For the 2nd the changes seem to be too major and I'm unfamiliar with the code base of both projects so I wasn't able to spot the proper change but there are withContext HOC and useDeck hook now exported from mdx-deck that are probably the way to go.

**Comment by mbilokonsky** [comment]
Just hit this too, which is a bummer because this was going to be a perfect tool for the deck I'm building!

**Comment by mbilokonsky** [comment]
Just hit this too, which is a bummer because this was going to be a perfect tool for the deck I'm building!

**Comment by pomber** [comment]
I'm planning to do a big refactor (and add more features), but I'm currently busy with other things. So the ETA is end of April.

**Comment by mbilokonsky** [comment]
awesome, thanks!

**Comment by emirotin** [comment]
@mbilokonsky use mdx-deck ^1.10.0 it works nice, the docs are here https://github.com/jxnblk/mdx-deck/tree/v1.10.2/docs

**Comment by madrus** [comment]
> 1.10.0
Works with inline code but not with code snippets like `code={require("!raw-loader!./my-snippet.js")}`. `code` parameter expects a string and not an object (error message).

**Comment by finish8** [comment]
> > 1.10.0
> > Works with inline code but not with code snippets like `code={require("!raw-loader!./my-snippet.js")}`. `code` parameter expects a string and not an object (error message).

Same issue as you.

**Comment by christopherjbaker** [comment]
@madrus @finish8 use `code={require("!raw-loader!./my-snippet.js").default}` instead

**Comment by madrus** [comment]
> @madrus @finish8 use `code={require("!raw-loader!./my-snippet.js").default}` instead

Wow! It works indeed. Thanks!

**Comment by finish8** [comment]
> @madrus @finish8 use `code={require("!raw-loader!./my-snippet.js").default}` instead

love you 😘

**Comment by aleclarson** [comment]
https://github.com/pomber/code-surfer/pull/54 works for me

**Comment by pomber** [comment]
> I'm planning to do a big refactor (and add more features), but I'm currently busy with other things. So the ETA is end of April.

Update: Now I have time to work on releasing a new version, so expect an alpha of code surfer v2 soon.

**Comment by pomber** [comment]
Fixed in v3 (well, it isn't compatible with mdx-deck v2, but it's compatible with mdx-deck v3)
