### ISSUE TITLE
Give Steps in limit and file load size

### ISSUE THREAD

**Issue by sachinsahu731** [pomber/code-surfer#56]
Hi, I have two things that I want to clear.

1) How to give multiple steps in range for example-:
`steps={[
    { range: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25], notes: "...headings" },
  ]}`
I want to put start and end range given below.Is their any way?
``steps={[
    { range: [10-25], notes: "...headings" },
  ]}``

2)  What is the file size we can load I have a file in 3097 kb (49866 Lines). But the chrome getting hanged when I try to load this file

**Comment by pomber** [comment]
1. See https://codesurfer.pomb.us/#focus  
2. The max file size depends on the user's ram
