### ISSUE TITLE
pre styles from theme?

### ISSUE THREAD

**Issue by karlhorky** [pomber/code-surfer#60]
Somewhat related to #52, it would be nice to be able to style the `pre` element, maybe via the MDX-Deck `theme.pre` configuration object.

I see that a version of this is being implemented for V2 (https://github.com/pomber/code-surfer/pull/58/files#diff-5679de880b7a5d62961675e36dab6ad0R33), so I suppose this will not be a priority for releasing before that.

My personal use case for this is just setting a simple `line-height` on the `pre`, which can be resolved via either #52 or maybe in the future, FormidableLabs/prism-react-renderer#37.

**Comment by pomber** [comment]
Yes, I'm focusing 100% on finishing the v2 PR.
But if you need it and want to send a PR I could publish it as a new pre-v2 version.

**Comment by pomber** [comment]
Should be fixed in v3 (with https://codesurfer.pomb.us/#themes)

**Comment by karlhorky** [comment]
Great, thanks! I'll try it when I get a chance :)

By the way, for some reason the hash doesn't scroll down the page when I click on your link above (is it maybe client-side rendered or something?)

**Comment by pomber** [comment]
Yes, it's either that or the demo iframe stealing focus on load. The docs page has several bugs, I need to work on it a bit more.

**Comment by karlhorky** [comment]
Hm, just coming back to this now, and I don't think this is fixed with v3 themes.

I'm trying to set `line-height` on `pre` and `code`, and while it does apply those styles to the elements, it does not create the effect of line height on each individual line.

Opened a new issue: https://github.com/pomber/code-surfer/issues/117
