### ISSUE TITLE
Columns instead of Tokens

### ISSUE THREAD

**Issue by kolibri** [pomber/code-surfer#61]
Hey peoples.

This is more or less a feature idea, or feature change idea.
Currently, we can select tokens inside rows to highlight them. Why not the columns of the row?
To be honest, after seeing the code example for this feature, I totally assumed it is already this way, so it it took a while to figure out, that there is a reason, why someone named columns "tokens" o_O.

The pragmatic usage would be to be language independent.
We could use this for broken code examples or unsupported/not fully supported languages.
Or in cases, where We just want to highlight something else then tokens.

I also have some case with a template with mixed languages (`*.ini.j2`), that would be solved by not relying on a tokenizer (I want to highlight only `{{ git_user_email }}` and `{{ git_user_name }}`: 

```
import { CodeSurfer } from "mdx-deck-code-surfer"
export { components } from "mdx-deck-code-surfer"

` ` `ini
# gitconfig.j2
[user]
    email = {{ git_user_email }}
    name = {{ git_user_name }}
[core]
    excludesfile = {{ ansible_user_dir }}/.gitignore
    editor = nano
----
*
3[13:33], 3[12:32] > use variable from playbook
` ` `
---
```

I know, this would be a breaking change, unless there is a nice way to use both ideas.
But, what do you think about this?

Have a nice day
 ko

**Comment by pomber** [comment]
I'm working exactly on this change in #58 at the moment :)

Your example will look like this:
~~~
```ini 3[13:33],4[12:32] subtitle="use variable from playbook"
# gitconfig.j2
[user]
    email = {{ git_user_email }}
    name = {{ git_user_name }}
[core]
    excludesfile = {{ ansible_user_dir }}/.gitignore
    editor = nano
```
~~~

**Comment by pomber** [comment]
Do you want to try the v2 alpha? Here is a codesandbox with your use case: https://codesandbox.io/s/yw127rqw5z

**Comment by kolibri** [comment]
I only wanted to look for the branchname of the v2-branch to give it a try, and you already provided a working example with my code. This is above awesome! Thank you.

**Comment by pomber** [comment]
Fixed in v3
