### ISSUE TITLE
progress prop

### ISSUE THREAD

**Issue by souporserious** [pomber/code-surfer#62]
Hello 👋 

First, thank you for such a wonderful library! I'm really excited for the V2 release. Apologies if this is too soon to file an issue for, but I was curious about the possibility of adding a `progress` prop. I think it could be really cool for using code-surfer outside of MDX and for landing pages, or even walking through API documentation. An example I could see is something similar to the latest docs page for [SwiftUI](https://developer.apple.com/tutorials/swiftui/creating-and-combining-views) where scroll progress could animate between sections of code with explanations.

Taking the example from the README, it might look something like the following:

```jsx
<CodeSurfer
  steps={[
    { notes: "Start with this note"},
    { lines: [6], notes: "Note for the first step" },
    { range: [5, 9] },
    { tokens: { 9: [3, 4, 5] }, notes: "Note for the third step" }
  ]}
  progress={0.25}
/>
```

I'm thinking `progress` would always be from 0-1. So in the case above it would show step 2, then the progress could be interpolated by something like `react-spring` for transitioning to the next step. One thing that seems like it might be hard is the individual animations that are all going on and how to hook that up to one progress prop.

I haven't taken a look at the code that's powering all of this yet, so I imagine it might not be very practical to rearchitect things to achieve this functionality, but if this sounds like something useful I would be happy to help and start a PR 😊.

**Comment by pomber** [comment]
Hi. Right now I'm focusing only on mdx-deck but I think I'll add some kind of support for this use case later. See this comment https://github.com/pomber/code-surfer/pull/58#issuecomment-494783203

**Comment by pomber** [comment]
The progress prop is available in the (undocumented) package @code-surfer/standalone@3.0.0.
See the usage [here](https://github.com/pomber/code-surfer/blob/0f825b0b2b421dc0a2f3e91901fd5ad75f012cac/sites/book/src/basic.story.js#L30)

**Comment by souporserious** [comment]
This is so awesome! Thank you for the amazing work on this! 🙏
