### ISSUE TITLE
Customize offOpacity in animations

### ISSUE THREAD

**Issue by mhartington** [pomber/code-surfer#63]
Hi there! Thanks for the awesome component.

Currently in the v2 branch, it seems that the `offOpacity` for code that is not focused is hard coded to `0.3`. Is there any objection to either: 

- Moving this to the syntax theme?
- exposing this as a prop on a component (code-surfer, code, etc)?

Depending on the display/theme/other factors, `0.3` doesn't really fade the code out as much.

If there's a better way to handle this, I'd be happy to send a PR.

**Comment by pomber** [comment]
Reading the offOpacity from the theme shouldn't be difficult. I'll add it to the PR.

Ideally I'd like to add custom focus/not-focus styles to allow, for example, highligthing lines by changing the background instead of the opacity. But, at the moment, that's harder because of the custom animation pseudolibrary that I'm using.

**Comment by alpinegizmo** [comment]
I'd like to see something a little more general purpose than being able to customize the offOpacity. I'd like to be able to experiment with different ways of highlighting the focused region -- and for printing, I'd like to be able to ignore the focus and simply print everything undecorated.

I realized it's an old school way of thinking, but I'd be happy with classes that mark the focused and unfocused divs/spans, or something equivalent.

But reading the offOpacity from the theme would already be quite useful.

**Comment by mhartington** [comment]
Since this has been implemented, I'm closing the issue

**Comment by pomber** [comment]
Thanks. For the record, it's documented [here](https://github.com/pomber/code-surfer#custom-styles) (`unfocused.opacity`).
