### ISSUE TITLE
mdx-deck v3 support

### ISSUE THREAD

**Issue by sibelius** [pomber/code-surfer#64]
will code surfer v2 works with mdx-deck v3?

**Comment by JJ** [comment]
This is probably the reason why this:
```
Can't resolve 'mdx-deck-code-surfer' in '/home/jmerelo/.nvm/versions/v8.12.0/lib/node_modules/mdx-deck/.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir'
```

fails, right?

**Comment by ais-one** [comment]
```
// mdx-deck: 3.0.9
// mdx-deck-code-surfer: 0.5.5

Generating SSR bundle failed

Can't resolve 'styled-components' in 'C:\Users\Aaron_Gong\test\ds\abc\node_modules\mdx-deck-code-surfer\dist'
```

**Comment by pomber** [comment]
> will code surfer v2 works with mdx-deck v3?
yes!

the hardest part with mdx-deck v3 is importing raw code from other files, so I'm not sure if we are going to support it yet.

**Comment by alpinegizmo** [comment]
Will code-surfer v2 continue to work with mdx-deck v2? So far I haven't been able to mdx-deck v3 working well enough to completely switch over. I'm happily using code-surfer 2.0.0-alpha.10 with mdx-deck 2.4, and hope v2 compatibility hasn't been abandoned.

**Comment by pomber** [comment]
I think v2.0.0-alpha.10 will be the last version that works with mdx-deck v2 (mdx-deck v2 and v3 are incompatible and I don't want to maintain two code surfer versions). Sorry.
What problems do you have with mdx-deck v3?

**Comment by alpinegizmo** [comment]
Working with the mdx-deck v3 cli, I've run into problems dealing with Theme UI. Doesn't seem to be quite as flexible as what we had before. I haven't yet figured how to fully recreate the heavily customized theme I put together for v2.

What I really need to do is figure out how to get mdx-3 running in a gatsby site, but I've already spent a lot of time struggling to get gatsby to behave. Been having the problems reported in https://github.com/jxnblk/mdx-deck/issues/414, among others. 

I think the biggest problem here is that gatsby is rather complex and for those of us unfamiliar with this whole ecosystem, there's an awful lot to learn just to make some slides. Everywhere I turn nothing in gatsby seems to work entirely as documented. mdx-deck without gatsby was easier to deal with.

**Comment by alpinegizmo** [comment]
@pomber When you say "the hardest part with mdx-deck v3 is importing raw code from other files, so I'm not sure if we are going to support it yet", does that mean that this sort thing isn't going to work?

```
<Code 
  lang='java'
  focus='1:18'
  code={require("!!raw-loader!../examples/process-function/context.java").default}
/>
<Code 
  lang='java'
  focus='7:8'
  code={require("!!raw-loader!../examples/process-function/context.java").default}
/>
```

I've succeeded in upgrading my project to mdx-deck v3, and am quite happy with the results now. Except that I'm getting `ReferenceError: require is not defined` errors in the cases like the ones above. Is there a workaround?

**Comment by alpinegizmo** [comment]
Perhaps there's a better answer, but I got things working by doing this:

```
import { Code, CodeSurferLayout } from "code-surfer"
import "prismjs/components/prism-java"

import contextJava from "!!raw-loader!../examples/process-function/context.java"

<CodeSurferLayout>
<Code
  lang='java'
  focus='1:18'
  code={contextJava}
/>
<Code 
  lang='java'
  focus='7:8'
  code={contextJava}
/>
</CodeSurferLayout>
```

**Comment by luckydonald** [comment]
@alpinegizmo  Using your workaround with the latest version makes everything go blank, all the other slides disappear too.

**Comment by pomber** [comment]
Fixed in Code Surfer v3
