### ISSUE TITLE
can't display code while create project with npx create-code-surfer-deck

### ISSUE THREAD

**Issue by aisy** [pomber/code-surfer#66]
When I create a project using the npx create-code-surfer-deck command and there is an error like this when I use code like this:

`<Code
   code = {require ("!! file-loader! ./ codes / fetchIntro / callFetch"). default}
/>`

and error is :
`TypeError: Cannot read property 'dimensions' of undefined` 

fyi: 
Previously I made a project using the npx create-code-surfer-deck command and it worked fine

**Comment by pomber** [comment]
Have you tried using raw-loader instead of file-loader?

**Comment by aisy** [comment]
Yes..
but same result, 
i'm using same code with previous project like this :

`<CodeSurferLayout>
   <Code
     code={"!!raw-loader!./src/codes/App.js"}
   />
</CodeSurferLayout>`

**Comment by pomber** [comment]
Does it also happen when you use the Code component without importing code from another file? Maybe it's the Code component that is broken.

**Comment by melcor76** [comment]
This is happening to me as well but it worked before.
I'm thinking some mdx dependencies changed when I started a new project.

**Comment by pomber** [comment]
> I'm thinking some mdx (or other) dependencies changed when I started a new project.

I haven't tried it yet, but that could be the reason. The last version of mdx is probably wrapping the Code element making code surfer fail.

I thought I pinned the versions to avoid this kind of problems, but I'm bad with dependencies. 

If anyone wants to send a PR to fix it in create-code-surfer-deck I'll merge it, if not I'm updating it to v3 soon.

**Comment by pomber** [comment]
Should be fixed in v3 (see https://codesurfer.pomb.us/#import-code)
