### ISSUE TITLE
"showNumbers" doesn't work in 2.0.0-alpha.8

### ISSUE THREAD

**Issue by lucacavallaro** [pomber/code-surfer#67]
How can I enable the line numbers in code surfer 2.0.0-alpha.8 with the new API? 

I tried this but it doesn't work

```
```go title="Hello, World" showNumbers="true"
package main

import "fmt"

func main() {
  fmt.Println("Hello, World")
}

```

**Comment by mhartington** [comment]
I find myself also needing this functionality. Is there any plan to add this to v3?
