### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by jamiebuilds** [pomber/code-surfer#7]
I feel like you could easily add a syntax to this tool

### Example Syntax

````md

```js
export function add(augend, addend) {
  return augend + addend;
}
---
* > Let's take a look at the add() function
1:17-1:36 > We've got our function signature here
1:21-1:27, 2:10-16 > The augend is the number to which others are added
1:29-1:35, 2:19-25 > The addend is a number which is added
2:3-2:25 > The function returns the result of the two
* > And that's the add function!
```
````

### Syntax Explainer

Specify the steps after the code by using a `---` or some other signifier.

````
```js
<code>
---
<steps>
```
````

Each step has some ranges and notes:

````
<ranges> > <notes>
1:10-2:20 > Here are some **notes**
````

Use `*` as your range to zoom out on everything:

````
*
````

Select a range:

````
<line>:<column>-<line>:<column>
1:10-2:20
````

Select multiple ranges:

````
<range>, <range>, <range>
1:10-2:20, 3:30-4:40
````

**Comment by pomber** [comment]
I like it! Do you know if there's something similar somewhere to use as a reference?  
I may try this after fixing some bugs and adding more docs.

**Comment by jamiebuilds** [comment]
I wrote a parser for the source position syntax before, I can publish it as an npm package real quick.

**Comment by kutyel** [comment]
Wow @jamiebuilds that is a great idea! 🎉 I'll improve the deck experience so much! Whenever the parser is published I can give this a try @pomber if you are too busy 😉 I'm here to help!

**Comment by jamiebuilds** [comment]
https://github.com/jamiebuilds/source-selection-syntax

**Comment by pomber** [comment]
Check it out here: https://codesurfer.js.org/sample/#9
