### ISSUE TITLE
Using CodeSurfer in tsx files

### ISSUE THREAD

**Issue by AashJ** [pomber/code-surfer#75]
Hi there! Great work on CodeSurfer!

One of my websites uses Next.js + React + Typescript. I'd like to use CodeSurfer as a React Component within an existing tsx file. Is there any documentation on how to do that?

**Comment by pomber** [comment]
Hey, thanks!

I think it's supported. Try https://github.com/pomber/code-surfer/#languages, and let me know.

**Comment by AashJ** [comment]
Sorry -- i'm not asking how to use a tsx file within CodeSurfer, but rather the other way around. I want to use CodeSurfer as a React Component within an existing component (i'm not doing the typical MDX + gatsby setup)

**Comment by pomber** [comment]
Oh, you can use the `@code-surfer/standalone` package, but it's undocumented. There are some usage examples in the storybook folder, for example: https://github.com/pomber/code-surfer/blob/master/sites/book/src/basic.story.js

**Comment by AashJ** [comment]
Great! I'll try it out 👍
