### ISSUE TITLE
Is there any plan to improve performance?

### ISSUE THREAD

**Issue by TroyTae** [pomber/code-surfer#93]
Hello, thank you for making lovely library :)
I wanna ask about performance improvement plan.
![image](https://user-images.githubusercontent.com/20078201/85671323-b9984780-b6fc-11ea-94c7-f2c1f8b06d63.png)
`fade` and `expand` animation is good but `move-left` animation(when inserting code) isn't smooth.
It's fine at first, but it gets weird when the code stops at the end.
Do you have plan about this??

**Comment by pomber** [comment]
Hey, I do have plans for a more performant approach, but instead of refactoring Code Surfer I may move the code to another project I'm working on ([Code Hike](https://github.com/code-hike/codehike)). Not sure yet.

**Comment by TroyTae** [comment]
It's cool! I'll follow twitter of code hike for tracking update.
If you need help in development, please tell me :)
